# fly.toml app configuration file generated for compact-playground on 2026-03-12T00:58:19Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'compact-playground'
primary_region = 'ams'

[build]
  dockerfile = 'Dockerfile'

[mounts]
  source = "cache_data"
  destination = "/data/cache"
  initial_size = "1gb"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[checks]
  [checks.health]
    port = 8080
    type = 'http'
    interval = '30s'
    timeout = '10s'
    grace_period = '30s'
    path = '/health'

[[restart]]
  policy = 'on-failure'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '1024mb'
  cpus = 1
